### ISSUE TITLE
New users can no longer sign up for DarkSky's API

### ISSUE THREAD

**Issue by VeryColdAir** [blaxbb/renowatch-pebble-modified#4]
Apple has bought DarkSkys, and as of March 31st, 2020, they are no longer allowing new users to sign-up for the API. For existing users, the API will be supported until the end of 2021.

![image](https://user-images.githubusercontent.com/20274614/80116288-66aee200-854b-11ea-993f-cee2be72c346.png)

Is it possible that the api could be switched to [OpenWeather's API](https://openweathermap.org/api), which is likely to be around longer?

**Comment by blaxbb** [comment]
should be fixed with 893764dc8a0a9e5d26

I only tested it for a few minutes, but it should be fine
