### ISSUE TITLE
Doesn't seem to work - new user

### ISSUE THREAD

**Issue by arainot** [blaxbb/renowatch-pebble-modified#7]
Hi,

I just tried to make weatherland work, I got an API key and then installed the pbw file on my phone. I waited ~2h for the API to activate. 

To be precise I replaced the API_KEY to API_KEY = "1234567786864554";   (whatever the number I have).

But on the watch, nothing happens, the background is grey and the temperature doesn't show. 
I tried setting the city by name, coordinates and city number from the openweathermap website. 

Do you have a city name that works for you to see if it works now for me please?

**Comment by blaxbb** [comment]
I never actually set up using the location field from the settings window, it should have grabbed it automatically.

Either way, I pushed a new commit which should use the settings field correctly using the format ex: London,uk or see https://openweathermap.org/current#name

Hopefully that works.
